#!/bin/bash
# author:kyle thomas
# USAGE: $journal [TOPIC_NAME1 TOPIC_NAME2 ..]
#- this journal is the "$blah"-script plus the line vim $JOURNAL
JOURNAL="/home/thomasky/Downloads/journal/contents.tex"
echo "" >> $JOURNAL
echo "\\section*{ `/usr/local/bin/kydate` }" >> $JOURNAL
echo "\\subsection*{ ${@:1} }" >> $JOURNAL
