#!/bin/bash
ROLLJOURNALPWD=`pwd`
ROLLJOURNALPATH=~/journal/
ROLLJOURNALFILE=journal.tex
cd $ROLLJOURNALPATH
# compile journal to pdf continuously from bg
latexmk -pvc -pdf $ROLLJOURNALFILE &
cd $ROLLJOURNALPWD
unset ROLLJOURNALPWD
unset ROLLJOURNALPATH
unset ROLLJOURNALFILE
