#!/bin/bash
rolljournalpwd=`pwd`
rolljournalpath=~/journal/
rolljournalfile=journal.tex
cd $rolljournalpath
# compile journal to pdf continuously from bg
latexmk -pvc -pdf rolljournalfile &
cd $rolljournalpwd
unset rolljournalpwd
unset rolljournalpath
unset rolljournalfile
